apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: sample-app
build:
  artifacts:
    - image: abitvolatile/advertisements-service
      context: ads-service/src
    - image: abitvolatile/discounts-service
      context: discounts-service/src
    - image: abitvolatile/store-frontend
      context: store-frontend/src
  tagPolicy:
    envTemplate:
      template: "{{.TAG}}"
deploy:
  kubectl:
    manifests:
      - ads-service/k8s-manifest/*.yaml
      - database/k8s-manifest/*.yaml
      - discounts-service/k8s-manifest/*.yaml
      - store-frontend/k8s-manifest/*.yaml
profiles:
  - name: local-dev
    activation:
    - kubeContext: kind
  - name: stage