---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: demo-app
  labels:
    service: frontend
    app: ecommerce
  name: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    service: frontend
    app: ecommerce
  type: LoadBalancer